gui:
  showBottomLine: false
  showCommandLog: false
  showFileTree: true
  showIcons: true
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#8aadf4'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    searchingActiveBorderColor:
      - '#eed49f'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitFgColor:
      - '#8aadf4'
    cherryPickedCommitBgColor:
      - '#494d64'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
  authorColors:
    '*': '#b7bdf8'

os:
  editPreset: "nvim-remote"
  copyToClipboardCmd: "tmux load-buffer -"
